---
- hosts: localhost
  connection: local
  vars:
    image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
    container_name: build_container
    image_name: gpt2:1
  tasks:
    - name: Make the base image available
      docker_image:
        name: "{{ image }}"


    - name: Install python into docker container
      docker_container:
        name:  "{{ container_name }}"
        command: apt install -y python3

    - name: Enable root
      docker_container:
        name:  "{{ container_name }}"
        command: passwd -u root

    - name: Create docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        command: sleep infinity

    - name: Add container to host group
      add_host:
        hostname: "{{ container_name }}"
        ansible_connection: docker
        #        ansible_python_interpreter: /usr/bin/python3


- hosts: build_container
  roles:
          - gpt2

- hosts: localhost
  connection: local
  vars:
    image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
    container_name: build_container
    image_name: gpt2:1
  tasks:
    - name: Commit docker conainer
      shell: docker commit \
        -c 'CMD ["python", "run_language_modeling.py", "--output_dir=output", "--model_type=gpt2", "--model_name_or_path=gpt2", "--do_train", "--train_data_file=$TRAIN_FILE", "--do_eval","--eval_data_file=$TEST_FILE", "--per_gpu_train_batch_size=1", "--per_gpu_eval_batch_size=1", "--num_train_epochs=9", "--save_steps=10000"]' \
       "{{ container_name }}" "{{ image_name }}"

    - name: Remove container
      docker_container:
        name: "{{ container_name }}"
        state: absent
